#ifndef ATOM_BASIC_CONTAINER_QUOTE_HPP
#define ATOM_BASIC_CONTAINER_QUOTE_HPP


/** @file
 * @brief File contains implementation of Quote, TwoWayQuote, and TwoWayQuote builder
 *
 *
 */

namespace atom::basic::detail
{

    /**
     * @brief Definition of quote is a Price and Quantity pair.
     *
     * This is a container, which contains a Price and the Quantity available at
     * that given price.
     *
     * @tparam V is the type of price, it can be double or User defined Price type
     * which may also contains information of currency of given Price. Constrains on
     * V is that it must be comparable
     *
     * @tparam Q is the type of quantity, hence it should be unsigned. 
     *
     * \todo need to make Quote comparable with eachothers in able to build up a order book.
     *  What needed to be achieved is
     * - Compare by Price
     * - Combine if price are the same
     *
     */
    template<typename V, typename Q>
    class Quote {
    public:
        /**
         *@brief Default Constructer is set to default
         *
         * Default Constructer is autometically generated by compiler.
         */
        Quote() = default;
        /**
         *@brief const& Constructer
        *
        * overloaded const& constructer
        */
        Quote(const V& value, const Q& qty);
        /**
         *@brief && Constructer
         *
         * overloaded && constructer
         */
        Quote(V&& value, Q&& qty);
        
        /**
         * @brief get value
         *
         * @return V return by value.
         */
        const auto value() const;
        /**
         * @brief get quantity
         *
         * @return Q return by value.
         */
        const auto qty() const;
        
    private:
        V value_;
        Q qty_;
    };
    
    template<typename V>
    class TwoWayQuote {
    public:
        using value_type = V;
    public:
        TwoWayQuote() = default;
        template<typename T,
            typename S,
            std::enable_if_t<
                atom::traits::is_optional_of_v<T, V>&&
                    atom::traits::is_optional_of_v<S, V>,
                std::nullptr_t
            > = nullptr
        >
        TwoWayQuote(T&& bid, S&& ask);

        const auto bid() const;
        const auto ask() const;
        const auto bidQty() const;
        const auto askQty() const;
        const auto hasBid() const;
        const auto hasAsk() const;

    private:
        std::optional<V> bid_;
        std::optional<V> ask_;
    };

    template<typename V, typename Q>
    class TwoWayQuoteBuilder {
    public:
        using value_type = V;
        using qty_type = Q;
    public:
        TwoWayQuoteBuilder() = default;
        TwoWayQuoteBuilder(const TwoWayQuoteBuilder&) = delete;
        TwoWayQuoteBuilder(TwoWayQuoteBuilder&&) = delete;
        TwoWayQuoteBuilder& operator =(const TwoWayQuoteBuilder&) = delete;
        TwoWayQuoteBuilder& operator =(TwoWayQuoteBuilder&&) = delete;

        operator TwoWayQuote<Quote<V, Q>>() const;

        template<typename T,
            std::enable_if_t<std::is_convertible_v<T, V>, std::nullptr_t> = nullptr
        >
            TwoWayQuoteBuilder& bidPrice(T&&);
        template<typename T,
            std::enable_if_t<std::is_convertible_v<T, V>, std::nullptr_t> = nullptr
        >
            TwoWayQuoteBuilder& askPrice(T&&);
        template<typename T,
            std::enable_if_t<std::is_convertible_v<T, Q>, std::nullptr_t> = nullptr
        >
            TwoWayQuoteBuilder& bidQty(T&&);
        template<typename T,
            std::enable_if_t<std::is_convertible_v<T, Q>, std::nullptr_t> = nullptr
        >
            TwoWayQuoteBuilder& askQty(T&&);
    private:
        std::optional<V> bidPrice_;
        std::optional<V> askPrice_;
        std::optional<Q> bidQty_;
        std::optional<Q> askQty_;
    };

#include "atom/basic/container/impl/quote.ipp"
} // namespace atom::basic


#endif //!ATOM_BASIC_CONTAINER_QUOTE_HPP
