name: Unit Test(Linux)

on: 
  push:
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Compiler gcc 10
      run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      shell: bash

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/_build

    - name: New Conan Profile
      working-directory: ${{runner.workspace}}/_build
      run: conan profile new default --detect
      shell: bash

    - name: Config conan
      working-directory: ${{runner.workspace}}/_build
      run: |
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan profile update settings.compiler.version=10 default
      shell: bash

    - name: Install Test Dependencies
      working-directory: ${{runner.workspace}}/_build
      run: conan install ${{github.workspace}} --build missing
      shell: bash

    - name: Configure CMake Linux
      shell: bash
      working-directory: ${{runner.workspace}}/_build
      run: cmake $GITHUB_WORKSPACE \
      env:
        CC:   gcc-10
        CXX:  g++-10


    - name: Build
      working-directory: ${{runner.workspace}}/_build
      shell: bash
      run: cmake --build . -j 8

    - name: CPP Unit Test
      working-directory: ${{runner.workspace}}/_build
      shell: bash
      run: ctest -R atom_test --verbose --timeout 600
